---
- name: Banner
  hosts: all
  become: true

  tasks:
    - name: Update banner
      lineinfile:
        path: /etc/motd
        regexp: '# Your banner goes here$'
        line: 'Welcome to my server!'
